### ISSUE TITLE
Titan Framework Loaded Twice

### ISSUE THREAD

**Issue by julien731** [siamkreative/Slick-Carousel-Reloaded#12]
The Titan Framework is currently loaded twice. First by the autoloader in the plugin, second with the Titan Framework plugin that is required to run Slick Carousel Reloaded.

This actually triggers an error (in my environment at least).

![image](https://cloud.githubusercontent.com/assets/1441024/14809386/d9f80c5e-0bb6-11e6-9263-6f01f0b7583f.png)
## Solutions

Obviously, one version of TF must be removed. [Best practices would suggest keeping the version that's autoloaded](https://make.wordpress.org/plugins/2016/03/01/please-do-not-submit-frameworks/) but any one version can be removed.
### Removing the Autoloaded Version

Because this version seems to be used solely for checking if TF is present, what's really useful is the `TitanFrameworkChecker` class. This class could simply be extracted and added in the plugin. It doesn't really need to be updated anyways.
### Removing the Plugin Version

In this case, the only thing needed is to remove the call to `titan-framework-checker.php`.

**Comment by siamkreative** [comment]
http://www.titanframework.net/embedding-titan-framework-in-your-project/

> Create a folder named `titan-framework` in your project and put all the framework code there. (important: the PHP scripts should be inside the `titan-framework` folder)
> Afterwards, in your functions.php or your main plugin script, add the code below:
> 
> ``` php
> require_once( 'titan-framework/titan-framework-embedder.php' );
> ```
